---
- hosts: localhost
  gather_facts: no
  connection: local
  become: false

  collections:
    - community.kubernetes


  tasks:
    - name: Install docker-py
      pip: name=docker-py

    - name: Build Docker image from Dockerfile
      docker_image:
        name: web
        path: app
        state: build

    - name: Deploy Hello App 
      k8s:
        definition:
          state: present
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            labels:
              app: web
            name: web
            namespace: default
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: web
            strategy:
            template:
              metadata:
                labels:
                  app: web
              spec:
                containers:
                - image: web:latest
                  imagePullPolicy: IfNotPresent
                  name: hello-app
                  ports:
                  - containerPort: 5000
          
    - name: Create an Ingress resources
      k8s:
        state: present
        definition:
          apiVersion: extensions/v1beta1
          kind: Ingress
          metadata:
            name: web-ingress
            namespace: default
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/rewrite-target: /$1
          spec:
            rules:
              - host: hello-isazi.co
                http:
                  paths:
                    - path: /
                      backend:
                        serviceName: web
                        servicePort: 5000

    - name: Create a Service for Hello App.
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            labels:
              app: web
            name: web
            namespace: default
          spec:
            type: LoadBalancer
            ports:
            - port: 5000
              targetPort: 5000
            selector:
              app: web


